### PR TITLE
It's python, but works for me.

### PR DESCRIPTION
**Pull request by poing**
Here's some code that works with the Cloud Speech API BETA.  Basic functionality.  See the README for additional requirements.

### CODE REVIEW

**Comment by lardconcepts** [comment]
Aaaggh! Thank you! I wish I had noticed this yesterday before I stayed up until midnight making almost the same! Good to know we came to almost identical conclusions but your code is neater 👍 

Thank you

**Comment by poing** [comment]
Glad to hear we reached identical conclusions.  How did you handle the AGI connection?

Since the new API is Python, any plan to move this repo away from Perl?

BTW: You can probably close issue #27

**Comment by lardconcepts** [comment]
Hi @poing - pyst2. I'm still tweaking, but I'll put something up later.

Connection is via pyst2.

**Comment by poing** [comment]
@lardconcepts, I actually had to [fix](https://github.com/rdegges/pyst2/commit/5f37f3ee6132b69e9502e601dc9a9b556d9dfb74) PYST2.  Getting it to pass Japanese back to the dial-plan was painful.  

Learning Python was _interesting_, but think got the hang of it now.  Just have to look out for default `ASCII` issues.

Sorry issue #27 was raised in your repo, thinking you had to close it.  Hopefully I answered the question.

**Comment by zaf** [comment]
Thank you for that, it's not practical tho to migrate to another language. So I will not merge it. I have implemented Cloud Speech API support in a new branch named cloud_api.

**Pull request closed without merging**
